export * from "./dist/ParseTree/Propbank/AutoArgument"
export * from "./dist/ParseTree/Propbank/TurkishAutoArgument"
export * from "./dist/Sentence/Propbank/SentenceAutoArgument"
export * from "./dist/Sentence/Propbank/SentenceAutoPredicate"
export * from "./dist/Sentence/Propbank/TurkishSentenceAutoArgument"
export * from "./dist/Sentence/Propbank/TurkishSentenceAutoPredicate"
export * from "./dist/Sentence/FrameNet/SentenceAutoFramePredicate"
export * from "./dist/Sentence/FrameNet/TurkishSentenceAutoFramePredicate"
