export * from "./AutoProcessor/ParseTree/Propbank/AutoArgument"
export * from "./AutoProcessor/ParseTree/Propbank/TurkishAutoArgument"
export * from "./AutoProcessor/Sentence/Propbank/SentenceAutoArgument"
export * from "./AutoProcessor/Sentence/Propbank/SentenceAutoPredicate"
export * from "./AutoProcessor/Sentence/Propbank/TurkishSentenceAutoArgument"
export * from "./AutoProcessor/Sentence/Propbank/TurkishSentenceAutoPredicate"
export * from "./AutoProcessor/Sentence/FrameNet/SentenceAutoFramePredicate"
export * from "./AutoProcessor/Sentence/FrameNet/TurkishSentenceAutoFramePredicate"
